minimumReleaseAgeExclude:
  - '@tuwaio/evm-sdk@0.2.1 || 0.2.2 || 0.3.0 || 0.4.0'
  - '@tuwaio/nova-connect@0.7.3 || 0.8.0 || 0.8.1'
  - '@tuwaio/nova-core@0.7.2 || 0.7.3 || 0.8.0 || 0.8.1'
  - '@tuwaio/nova-transactions@0.7.3 || 0.7.4 || 0.8.0 || 0.8.1'
  - '@tuwaio/satellite-evm@0.6.2 || 0.7.0 || 0.8.0'
  - '@tuwaio/satellite-react@0.6.3 || 0.7.0 || 0.8.0'
  - '@tuwaio/sdk@0.2.1 || 0.2.2 || 0.3.0 || 0.4.0'
  - '@tuwaio/siwx-server@0.4.2 || 0.4.3 || 0.5.1 || 0.6.0'
  - '@web3icons/common@0.11.52'
  - '@web3icons/react@4.1.23'
  - viem@2.57.2
  - '@tuwaio/pulsar-core@0.8.3 || 0.9.0 || 0.9.1'
  - '@tuwaio/quasar-sdk@0.2.1 || 0.3.0 || 0.4.0'
  - '@tuwaio/siwx-core@0.4.1 || 0.5.0 || 0.6.0'
  - '@tuwaio/siwx-evm@0.4.2 || 0.4.3 || 0.5.0'
  - '@tuwaio/siwx-react@0.4.1 || 0.5.1 || 0.6.0'
  - '@tuwaio/siwx-solana@0.4.2 || 0.4.3 || 0.5.0'
  - '@tuwaio/solana-sdk@0.2.1 || 0.3.0 || 0.4.0'
  - '@types/node@26.6.4'
  - framer-motion@13.5.1 || 14.0.0
  - motion-dom@13.5.1 || 14.0.0
  - '@tuwaio/orbit-core@0.4.0 || 0.5.0'
  - '@tuwaio/orbit-solana@0.4.0'
  - '@tuwaio/pulsar-evm@0.8.0 || 0.8.1'
  - '@tuwaio/pulsar-solana@0.9.0 || 0.9.1'
  - '@tuwaio/satellite-core@0.7.0 || 0.8.0'
  - '@tuwaio/satellite-solana@0.7.0 || 0.8.0'
  - motion-utils@14.0.0
