// A Ukrainian translation of Nova Transactions, which ships English only. Nova Connect ships its own
// (`ukrainianLabels` from `@tuwaio/sdk/nova-connect/i18n`). The type makes the translation complete: a missing key
// fails the build.
import type { NovaTransactionsLabels } from '@tuwaio/sdk/nova-transactions';

/** The `labels` prop of `NovaTransactionsProvider` in Ukrainian. */
export const ukrainianTransactionsLabels: NovaTransactionsLabels = {
  transactionsModal: {
    history: {
      title: 'Історія транзакцій',
      connectWalletTitle: 'Підключіть гаманець',
      connectWalletMessage: 'Підключіть гаманець, щоб побачити свої транзакції.',
      noTransactionsTitle: 'Транзакцій ще немає',
      noTransactionsMessage: 'Тут з’явиться історія ваших транзакцій у застосунку.',
    },
  },
  toast: {
    openTransaction: 'Відкрити транзакцію',
  },
  statuses: {
    pending: 'В обробці',
    confirmed: 'Підтверджено',
    success: 'Успішно',
    failed: 'Помилка',
    reverted: 'Скасовано мережею',
    replaced: 'Замінено',
    unknown: 'Невідомо',
    confirmationsLabel: 'Підтвердження',
  },
  hashLabels: {
    gelato: 'ID завдання Gelato',
    safe: 'Хеш транзакції Safe',
    erc4337: 'Хеш UserOp',
    original: 'Початковий хеш',
    replaced: 'Хеш заміни',
    default: 'Хеш транзакції',
    recentBlockhash: 'Останній blockhash',
    solana: 'Підпис',
  },
  txInfo: {
    started: 'Розпочато',
    network: 'Мережа',
    slot: 'Слот',
  },
  txError: {
    title: 'Помилка',
    copied: 'Скопійовано!',
  },
  validationError: {
    title: 'Помилка перевірки',
    field: 'Поле',
    copy: 'Скопіювати помилку',
    copied: 'Скопійовано!',
  },
  trackingModal: {
    title: 'Огляд транзакції',
    processing: 'Обробка...',
    close: 'Закрити',
    allTransactions: 'Усі транзакції',
    retry: 'Повторити',
    progressIndicator: {
      created: 'Створено',
      processing: 'Обробка',
      succeed: 'Успішно',
    },
  },
  trackedTxButton: {
    loading: 'Обробка...',
    succeed: 'Успішно',
    failed: 'Помилка',
    replaced: 'Замінено',
  },
  actions: {
    copy: 'Скопіювати адресу',
    viewOnExplorer: 'Переглянути в експлорері',
    close: 'Закрити',
    cancel: 'Скасувати',
    speedUp: 'Прискорити',
  },
  transactionDetails: {
    title: 'Деталі транзакції',
    subtitle: 'Повні дані виконання та статус у мережі.',
    metadata: 'Метадані',
    executionData: 'Дані виконання',
    adapter: 'Адаптер',
    submittedAt: 'Надіслано',
    finishedAt: 'Завершено',
    tracker: 'Трекер',
    connector: 'Конектор',
    confirmations: 'Підтвердження',
    txKey: 'Ключ транзакції',
    from: 'Від (відправник)',
    to: 'Кому (отримувач)',
    hash: 'Хеш транзакції',
    network: 'Мережа',
    inputData: 'Вхідні дані',
    payload: 'Корисне навантаження',
    context: 'Контекст',
    nonce: 'Nonce',
    value: 'Сума (raw)',
    maxFee: 'Макс. комісія за газ',
    maxPriorityFee: 'Макс. пріоритетна комісія за газ',
    solanaTitle: 'Дані виконання Solana',
    starknetTitle: 'Дані виконання Starknet',
    contextTitle: 'Контекст і навантаження',
    fee: 'Комісія',
    slot: 'Слот',
    instructions: 'Інструкції',
    recentBlockhash: 'Останній blockhash',
    contractAddress: 'Адреса контракту',
    actualFee: 'Фактична комісія',
    titleContext: 'Контекст заголовка',
    descriptionContext: 'Контекст опису',
    errorContext: 'Контекст помилки',
    fullPayload: 'Повне навантаження',
    replacedHash: 'Хеш заміни',
    syncStatus: {
      pending: 'Очікує синхронізації',
      pendingTooltip: 'У черзі на синхронізацію з хмарою',
      synced: 'Синхронізовано',
      syncedTooltip: 'Синхронізовано з Quasar Cloud',
    },
  },
};
